source 'http://rubygems.org'

gem 'rails', '3.0.20'

gem 'sqlite3'

group :development, :test do
  gem 'rspec-rails', '~> 2.11'
  gem 'spork', '~> 0.9.2'
  gem 'shoulda-matchers', '= 1.4.1'
  gem 'factory_girl', '~> 2.6.0'
  gem 'ffaker'
  gem 'webmock', '>= 1.9.0', :require => false
  gem 'capybara', '~> 2.0'
end